I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ScriptAndCases/Case_1/Case1script.rpy", line 323, in script
    Narrator"DEPOSITION DU TEMOIN"
Exception: Sayer 'Narrator' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ScriptAndCases/Case_1/Case1script.rpy", line 323, in script
    Narrator"DEPOSITION DU TEMOIN"
  File "D:\truc\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\truc\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Narrator' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Ace Attorney: Walter Romanng  Beta
Mon May 27 17:42:52 2024
